export const EVENTS = {
  // Mechanic Agent Events
  HARDWARE_FAILURE: "HARDWARE_FAILURE",
  SELF_HEALING_STARTED: "SELF_HEALING_STARTED",
  SELF_HEALING_SUCCESS: "SELF_HEALING_SUCCESS",
  SELF_HEALING_FAILED: "SELF_HEALING_FAILED",
  MAINTENANCE_REQUIRED: "MAINTENANCE_REQUIRED",
  DIAGNOSTIC_COMPLETE: "DIAGNOSTIC_COMPLETE",

  // Traffic Agent Events
  INCENTIVE_OFFERED: "INCENTIVE_OFFERED",
  CONGESTION_ALERT: "CONGESTION_ALERT",
  CONGESTION_CRITICAL: "CONGESTION_CRITICAL",
  DEMAND_SURGE: "DEMAND_SURGE",
  TRAFFIC_OPTIMIZED: "TRAFFIC_OPTIMIZED",

  // Logistics Agent Events
  STOCKOUT_PREDICTED: "STOCKOUT_PREDICTED",
  STOCKOUT_IMMINENT: "STOCKOUT_IMMINENT",
  INVENTORY_CRITICAL: "INVENTORY_CRITICAL",
  DISPATCH_INITIATED: "DISPATCH_INITIATED",
  DISPATCH_COMPLETED: "DISPATCH_COMPLETED",
  SUPPLY_OPTIMIZED: "SUPPLY_OPTIMIZED",

  // Energy Agent Events
  PRICE_SPIKE: "PRICE_SPIKE",
  PRICE_SPIKE_CRITICAL: "PRICE_SPIKE_CRITICAL",
  GRID_INSTABILITY: "GRID_INSTABILITY",
  TRADING_OPPORTUNITY: "TRADING_OPPORTUNITY",
  ARBITRAGE_EXECUTED: "ARBITRAGE_EXECUTED",
  ENERGY_OPTIMIZED: "ENERGY_OPTIMIZED",

  // Auditor Agent Events
  ANOMALY_DETECTED: "ANOMALY_DETECTED",
  COMPLIANCE_VIOLATION: "COMPLIANCE_VIOLATION",
  AUDIT_COMPLETE: "AUDIT_COMPLETE",
  DECISION_FLAGGED: "DECISION_FLAGGED",
  RISK_ASSESSMENT_HIGH: "RISK_ASSESSMENT_HIGH",

  // Station Events
  STATION_ONLINE: "STATION_ONLINE",
  STATION_OFFLINE: "STATION_OFFLINE",
  STATION_MAINTENANCE: "STATION_MAINTENANCE",
  QUEUE_UPDATE: "QUEUE_UPDATE",

  // User Events
  CHARGING_STARTED: "CHARGING_STARTED",
  CHARGING_COMPLETE: "CHARGING_COMPLETE",
  CHARGING_INTERRUPTED: "CHARGING_INTERRUPTED",
  PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
  PAYMENT_FAILED: "PAYMENT_FAILED",

  // System Events
  SYSTEM_ALERT: "SYSTEM_ALERT",
  SYSTEM_MAINTENANCE: "SYSTEM_MAINTENANCE",
  HEARTBEAT: "HEARTBEAT",
  STATUS_UPDATE: "STATUS_UPDATE",
  LOCATION_UPDATE: "LOCATION_UPDATE"
};

export const EVENT_SEVERITIES = {
  LOW: "low",
  MEDIUM: "medium", 
  HIGH: "high",
  CRITICAL: "critical"
};

export const AGENT_TYPES = {
  MECHANIC: "mechanic",
  TRAFFIC: "traffic", 
  LOGISTICS: "logistics",
  ENERGY: "energy",
  AUDITOR: "auditor"
};